### ISSUE TITLE
Ubuntu Error HTTP Error 404: NOT FOUND

### ISSUE THREAD

**Issue by gamedevsam** [Storj/DriveShare#6]
I'm getting errors when I try to follow the Ubuntu instructions on github, can anyone help me?
```
samuel@samuel-Inspiron-530:~$ dataserv-client --store_path="/media/samuel/My Book" --max_size=490GB build
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/messaging.py", line 45, in _url_query
    response = urllib.request.urlopen(req)
  File "/usr/lib/python3.4/urllib/request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: NOT FOUND

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/dataserv-client", line 10, in <module>
    cli.main(sys.argv[1:])
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/cli.py", line 153, in main
    return getattr(client, command_name)(**arguments)
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/api.py", line 174, in build
    rebuild=rebuild)
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/builder.py", line 118, in build
    self.on_generate_shard(shard_num + 1, seed, file_hash)
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/api.py", line 166, in _on_generate_shard
    self.messenger.height(cur_height)
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/messaging.py", line 115, in height
    height))
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/messaging.py", line 42, in _url_query
    headers = self._create_authentication_headers()
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/messaging.py", line 77, in _create_authentication_headers
    msg = self._get_node_address() + " " + header_date
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/messaging.py", line 70, in _get_node_address
    self._server_address = self.address()
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/messaging.py", line 91, in address
    data = self._url_query("/api/address", authenticate=False)
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/messaging.py", line 53, in _url_query
    raise exceptions.FarmerNotFound(self._server_url)
dataserv_client.exceptions.FarmerNotFound: Farmer not found at http://status.driveshare.org!
```

**Comment by gamedevsam** [comment]
Found fix on Slack chat:
```
Quick fix for people that get invalid address error, for Windows v.2.0.3:

1 reregister using the register command:

dataserv-client --url http://status.driveshare.org:5000 register

2 - Then run a build with --set_height_interval=1 to resume your address being displayed on the stats page at http://status.driveshare.org:5000/api/online. The command should be:

dataserv-client --url=http://status.driveshare.org:5000 --max_size=<MAX_DATA_SIZE_IN_BYTES> --store_path=<PATH TO FOLDER> build --set_height_interval=1 (edited)

3 - Then poll after that:

dataserv-client --url http://status.driveshare.org:5000 poll

ALTERNATIVELY if the above doesn’t work

1 - reregister using the register command:

dataserv-client --url http://status.driveshare.org:5000 register

2 - then delete 26 of your previously generated shard starting from the last generated, arrange the folder view by date modified so the last ones will be on top. Then build again, it should take really little time to do that.

dataserv-client --url=http://status.driveshare.org:5000 --max_size <MAX_DATA_SIZE_IN_BYTES> --store_path <PATH TO FOLDER> build

- Then your address should appear on the status page and you’ll be able to poll:

dataserv-client --url http://status.driveshare.org:5000 poll

There may be a few disconnects as the server is being worked on. (edited)
```
